# Generated by Django 2.0 on 2018-03-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='file_path',
            field=models.CharField(default='videos/darude.mp4', max_length=50),
        ),
    ]
