# Generated by Django 2.0 on 2018-03-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0002_clip_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='file_path',
            field=models.CharField(default='static/videos/darude.mp4', max_length=50),
        ),
    ]
