# Generated by Django 2.0 on 2018-03-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0004_clip_is360video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='file_path',
            field=models.CharField(default='videos/darude.mp4', max_length=50),
        ),
    ]
