# Generated by Django 2.0 on 2018-03-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0005_auto_20180324_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='file_path',
            field=models.CharField(default='clips/videos/darude.mp4', max_length=50),
        ),
    ]
