# Generated by Django 2.0 on 2018-03-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0008_auto_20180327_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='file_path',
            field=models.FilePathField(path='clips/videos'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='starRating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clip',
            name='thumb_path',
            field=models.FilePathField(path='clips/images'),
        ),
    ]
