# Generated by Django 2.0 on 2018-03-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene', models.CharField(max_length=10)),
                ('take', models.CharField(max_length=10)),
                ('starRating', models.CharField(max_length=10)),
            ],
        ),
    ]
