# Generated by Django 2.0 on 2018-03-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0006_auto_20180324_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='thumb_path',
            field=models.CharField(default='clips/images/darude.png', max_length=50),
        ),
    ]
