# Generated by Django 2.0 on 2018-03-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0007_clip_thumb_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='starRating',
            field=models.IntegerField(max_length=10),
        ),
    ]
