# Generated by Django 2.0 on 2018-03-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0009_auto_20180327_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='file_path',
            field=models.FilePathField(path='clips/static/clips/videos'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='thumb_path',
            field=models.FilePathField(path='clips/static/clips/images'),
        ),
    ]
